services:
  container:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
    image: paolomandica/ubuntu-22.04-deep-learning
    container_name: ubuntu-deep-learning
    volumes:
      - ${DATA_VOLUME}:/data
      - ${CODE_VOLUME}:/code
    stdin_open: true
    tty: true
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [gpu]
    shm_size: '256G'
