version: '3'
services:
  container:
    image: paolomandica/ubuntu-18.04-cluster
    container_name: ubuntu_test
    volumes:
      - /storage:/data_volume
      - /home/loki/paolo:/code_volume
    stdin_open: true
    tty: true
    command: /bin/bash
